//! Portable SQL statements carrying the same schema the `sqlite` format
//! writes, for loading a rating into an existing database.

use crate::error::Result;
use crate::report::{Report, TOOL_VERSION};
use std::fmt::Write as _;

/// Schema shared by the `sql` and `sqlite` formats.
pub const SCHEMA: &str = "\
CREATE TABLE IF NOT EXISTS assessment (
    id                        TEXT    NOT NULL,
    title                     TEXT    NOT NULL,
    notes                     TEXT,
    location                  TEXT,
    profile                   TEXT    NOT NULL,
    likelihood_sum            INTEGER NOT NULL,
    likelihood_average        REAL    NOT NULL,
    likelihood_band           TEXT    NOT NULL,
    technical_impact_average  REAL    NOT NULL,
    technical_impact_band     TEXT    NOT NULL,
    business_impact_average   REAL    NOT NULL,
    business_impact_band      TEXT    NOT NULL,
    overall_impact_average    REAL    NOT NULL,
    overall_impact_band       TEXT    NOT NULL,
    impact_basis              TEXT    NOT NULL,
    impact_used_average       REAL    NOT NULL,
    impact_used_band          TEXT    NOT NULL,
    severity                  TEXT    NOT NULL,
    derivation                TEXT    NOT NULL,
    tool_version              TEXT    NOT NULL,
    generated_at              TEXT    NOT NULL,
    PRIMARY KEY (id, generated_at)
);

CREATE TABLE IF NOT EXISTS factor_score (
    assessment_id  TEXT    NOT NULL,
    generated_at   TEXT    NOT NULL,
    factor_key     TEXT    NOT NULL,
    factor_name    TEXT    NOT NULL,
    factor_group   TEXT    NOT NULL,
    score          INTEGER NOT NULL,
    anchor         TEXT,
    assumed        INTEGER NOT NULL,
    PRIMARY KEY (assessment_id, generated_at, factor_key)
);
";

pub fn render(reports: &[Report]) -> Result<Vec<u8>> {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- OWASP risk rating, generated by riskforge {TOOL_VERSION}"
    );
    let _ = writeln!(out, "{SCHEMA}");

    for report in reports {
        let id = report.id();
        let generated_at = report.generated_at.to_rfc3339();

        let _ = writeln!(
            out,
            "INSERT INTO assessment VALUES ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, \
             {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {});",
            quote(&id),
            quote(&report.assessment.title),
            quote_opt(report.assessment.notes.as_deref()),
            quote_opt(report.assessment.location.as_deref()),
            quote(report.profile.as_str()),
            report.likelihood.sum,
            report.likelihood.rounded(),
            quote(report.likelihood_band().as_str()),
            report.technical_impact.rounded(),
            quote(report.technical_impact.band().as_str()),
            report.business_impact.rounded(),
            quote(report.business_impact.band().as_str()),
            report.overall_impact.rounded(),
            quote(report.overall_impact.band().as_str()),
            quote(report.impact_basis.as_str()),
            report.impact_used.rounded(),
            quote(report.impact_band().as_str()),
            quote(report.severity.as_str()),
            quote(&report.derivation()),
            quote(TOOL_VERSION),
            quote(&generated_at),
        );

        for entry in &report.assessment.scores {
            let _ = writeln!(
                out,
                "INSERT INTO factor_score VALUES ({}, {}, {}, {}, {}, {}, {}, {});",
                quote(&id),
                quote(&generated_at),
                quote(entry.factor.key),
                quote(entry.factor.name),
                quote(&format!("{:?}", entry.factor.group).to_lowercase()),
                entry.score,
                quote_opt(entry.factor.anchor(entry.score)),
                i32::from(entry.assumed),
            );
        }
        out.push('\n');
    }

    Ok(out.into_bytes())
}

/// Render a SQL string literal. Single quotes are doubled, which is the
/// standard escape, and control characters are stripped so no value can
/// break out of its literal or inject a statement terminator.
fn quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('\'');
    for character in value.chars() {
        match character {
            '\'' => out.push_str("''"),
            control if control.is_control() => out.push(' '),
            other => out.push(other),
        }
    }
    out.push('\'');
    out
}

fn quote_opt(value: Option<&str>) -> String {
    value.map(quote).unwrap_or_else(|| "NULL".to_string())
}
